server:
  port: 8080
#  servlet:
#    context-path: /chris 这里用于将项目路径指定为/chris下面
spring:
  application:
    name: Hello001Application #application名字
  profiles:
    active: dev # 开启端口
  mvc:
    favicon:
      enabled: false # 关闭默认图标
    date-format: "yyyy-MM-dd"
  thymeleaf:
    cache: false # 关闭模板引擎缓存
  messages:
    basename: i18n.login # 国际化文件配置
  datasource:
    username: root
    password: 123456
    # url->时区serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  type-aliases-package: top.chriszwz.Hello001.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
logging:
  level:
    top:
      chriszwz:
        Hello001:
          dao: debug
---
server:
  port: 8081
spring:
  profiles: dev

---
server:
  port: 8082
spring:
  profiles: test
